// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_w_WcJa8ySaYHJUPRm5vpiBSaSQyIRqA',
    appId: '1:85961217089:web:4088a3ef98ad4dcb47e2c0',
    messagingSenderId: '85961217089',
    projectId: 'jo-experience-app',
    authDomain: 'jo-experience-app.firebaseapp.com',
    storageBucket: 'jo-experience-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt4kUCUFJSb-ehoqR04H-ylldDW4zTgOg',
    appId: '1:85961217089:android:49b114b2af4c261d47e2c0',
    messagingSenderId: '85961217089',
    projectId: 'jo-experience-app',
    storageBucket: 'jo-experience-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ93cWiDp_5Q9s6ohc3PbBBkupA2rBEEA',
    appId: '1:85961217089:ios:c14194eb602bfb5c47e2c0',
    messagingSenderId: '85961217089',
    projectId: 'jo-experience-app',
    storageBucket: 'jo-experience-app.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ93cWiDp_5Q9s6ohc3PbBBkupA2rBEEA',
    appId: '1:85961217089:ios:c14194eb602bfb5c47e2c0',
    messagingSenderId: '85961217089',
    projectId: 'jo-experience-app',
    storageBucket: 'jo-experience-app.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_w_WcJa8ySaYHJUPRm5vpiBSaSQyIRqA',
    appId: '1:85961217089:web:d2d81ab37f87132d47e2c0',
    messagingSenderId: '85961217089',
    projectId: 'jo-experience-app',
    authDomain: 'jo-experience-app.firebaseapp.com',
    storageBucket: 'jo-experience-app.firebasestorage.app',
  );

}